parking:
  slot:
    rate: 25.0
    duration:
      hours: 1

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/parking_system
    username: postgres
    password: sohaibsohaib2
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 910327664002-svo7fsi7thcp853aashisdgav43i0ink.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: very_long_and_secure_jwt_secret_key_for_development_only_change_in_production_environment
  expiration: 86400000
  refresh-expiration: 604800000

logging:
  level:
    root: INFO
    com.parkingsystem: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: INFO

---
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:postgresql://localhost:5432/parking_system
    username: postgres
    password: sohaibsohaib2

jwt:
  secret: dev_environment_very_long_and_secure_jwt_secret_key_please_change_in_production
  expiration: 86400000
  refresh-expiration: 604800000

logging:
  level:
    root: DEBUG
    com.parkingsystem: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
